CC = gcc
CFLAGS = -Wall -Wextra -x c -std=c89
UNITY_DIR = ../../Unity

greet-with-errors:
	$(CC) $(CFLAGS) -o ~/bin/greet-with-errors greet-with-errors.c

copy:
	$(CC) $(CFLAGS) -o ~/bin/copy copy.c

copy-stdio:
	$(CC) $(CFLAGS) -o ~/bin/copy-stdio copy-stdio.c

random-access:
	$(CC) $(CFLAGS) -o ~/bin/random-access random-access.c

clean:
	rm foo bar data
