greet-with-errors:
	gcc -o ~/bin/greet-with-errors greet-with-errors.c

copy:
	gcc -o ~/bin/copy copy.c

copy-stdio:
	gcc -o ~/bin/copy-stdio copy-stdio.c

random-access:
	gcc -o ~/bin/random-access random-access.c

clean:
	rm foo bar data ~/bin/*
